name: 'QA'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 8 * * 1' # At 08:00 on Monday

env:
  php-tools: 'composer:v2'

jobs:
  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer cs

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer phpstan

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer test

  coverage:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer coverage
      - run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.2/php-coveralls.phar
          php php-coveralls.phar --verbose --config .coveralls.yml
